package com.example.greendao.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 8): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 8;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        BindingRequestBeanDao.createTable(db, ifNotExists);
        BindWatchEntityDao.createTable(db, ifNotExists);
        BroadCastBeanDao.createTable(db, ifNotExists);
        CallsTrafficBeanDao.createTable(db, ifNotExists);
        CareRemindBeanDao.createTable(db, ifNotExists);
        ContactsBeanDao.createTable(db, ifNotExists);
        CourseBeanDao.createTable(db, ifNotExists);
        EfenceBeanDao.createTable(db, ifNotExists);
        FareandFlowDataBeanDao.createTable(db, ifNotExists);
        LABlocationBeanDao.createTable(db, ifNotExists);
        LocationBeanDao.createTable(db, ifNotExists);
        MessageRecordBeanDao.createTable(db, ifNotExists);
        RunTimeCategoryBeanDao.createTable(db, ifNotExists);
        rusumeBeanDao.createTable(db, ifNotExists);
        ScheduleBeanDao.createTable(db, ifNotExists);
        WatchCardBeanDao.createTable(db, ifNotExists);
        WatchMapDevice_DeviceInfoDao.createTable(db, ifNotExists);
        WeatherBeanDao.createTable(db, ifNotExists);
        WIFIlocationBeanDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        BindingRequestBeanDao.dropTable(db, ifExists);
        BindWatchEntityDao.dropTable(db, ifExists);
        BroadCastBeanDao.dropTable(db, ifExists);
        CallsTrafficBeanDao.dropTable(db, ifExists);
        CareRemindBeanDao.dropTable(db, ifExists);
        ContactsBeanDao.dropTable(db, ifExists);
        CourseBeanDao.dropTable(db, ifExists);
        EfenceBeanDao.dropTable(db, ifExists);
        FareandFlowDataBeanDao.dropTable(db, ifExists);
        LABlocationBeanDao.dropTable(db, ifExists);
        LocationBeanDao.dropTable(db, ifExists);
        MessageRecordBeanDao.dropTable(db, ifExists);
        RunTimeCategoryBeanDao.dropTable(db, ifExists);
        rusumeBeanDao.dropTable(db, ifExists);
        ScheduleBeanDao.dropTable(db, ifExists);
        WatchCardBeanDao.dropTable(db, ifExists);
        WatchMapDevice_DeviceInfoDao.dropTable(db, ifExists);
        WeatherBeanDao.dropTable(db, ifExists);
        WIFIlocationBeanDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(BindingRequestBeanDao.class);
        registerDaoClass(BindWatchEntityDao.class);
        registerDaoClass(BroadCastBeanDao.class);
        registerDaoClass(CallsTrafficBeanDao.class);
        registerDaoClass(CareRemindBeanDao.class);
        registerDaoClass(ContactsBeanDao.class);
        registerDaoClass(CourseBeanDao.class);
        registerDaoClass(EfenceBeanDao.class);
        registerDaoClass(FareandFlowDataBeanDao.class);
        registerDaoClass(LABlocationBeanDao.class);
        registerDaoClass(LocationBeanDao.class);
        registerDaoClass(MessageRecordBeanDao.class);
        registerDaoClass(RunTimeCategoryBeanDao.class);
        registerDaoClass(rusumeBeanDao.class);
        registerDaoClass(ScheduleBeanDao.class);
        registerDaoClass(WatchCardBeanDao.class);
        registerDaoClass(WatchMapDevice_DeviceInfoDao.class);
        registerDaoClass(WeatherBeanDao.class);
        registerDaoClass(WIFIlocationBeanDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
